name: Smoke test Cloud Run

on:
  workflow_call:
    inputs:
      run_url:
        required: true
        type: string

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Smoke test (unauthenticated)
        shell: bash
        run: |
          set -euo pipefail
          URL="${{ inputs.run_url }}"
          echo "Testing $URL"
          CODE=$(curl -s -o /dev/null -w "%{http_code}" "$URL/")
          if [ "$CODE" != "200" ]; then
            echo "Expected 200, got $CODE"; exit 1
          fi
          echo "OK: $CODE"
